package dialog

import "github.com/docker/docker-agent/pkg/tui/help"

// dialogReferenceSections describes existing handlers, not a key registry.
// Keep aliases in canonical spelling; runtime availability is projected in ContextHelp.
func dialogReferenceSections() []help.Section {
	return []help.Section{
		{ID: "dialog.manager", Title: "Dialog safety", Entries: []help.Entry{
			{ID: "dialog.manager.semantic-cancel-top-not-affirmative", Keys: []string{"esc", "mouse ×", "outside left click"}, Description: "Semantic cancel top (not affirmative)", Condition: "Visible top dialog; Escape and × safely dismiss. Outside left click also cancels unless the dialog disallows it. Configured Quit instead requests exit confirmation through application routing."},
		}},
		{ID: "dialog.shared-actions", Title: "Action sections", Entries: []help.Entry{
			{ID: "dialog.shared-actions.enter-leave-actions-at-family-content-boundary", Keys: []string{"tab", "shift+tab"}, Description: "Enter/leave actions at family content boundary", Condition: "Enabled actions exist; Tab crosses at the outer content boundary, Shift+Tab in reverse."},
			{ID: "dialog.shared-actions.previous-next-enabled-action-wrapping", Keys: []string{"left", "up", "right", "down"}, Description: "Previous/next enabled action, wrapping", Condition: "Action section focused; skips disabled actions. Modified arrows are also consumed here."},
			{ID: "dialog.shared-actions.dispatch-original-selected-enabled-action-key", Keys: []string{"enter", "mouse action pill"}, Description: "Dispatch original selected enabled action key", Condition: "Action section focused, or a visible enabled action is clicked; Enter (including modified Enter) follows the selected action."},
		}},
		{ID: "dialog.shared-body", Title: "Dialog scrolling", Entries: []help.Entry{
			{ID: "dialog.shared-body.scroll-body", Keys: []string{"pgup", "pgdown", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll body", Condition: "Body viewport; footer wheel/scrollbar scrolling is separate."},
		}},
		{ID: "dialog.help", Title: "Help", Entries: []help.Entry{
			{ID: "dialog.help.scroll-read-only-content", Keys: []string{"up", "k", "down", "j", "pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll read-only content", Condition: "content"},
			{ID: "dialog.help.dismiss", Keys: []string{"esc", "enter", "q"}, Description: "Dismiss", Condition: "content"},
		}},
		{ID: "dialog.agent-details", Title: "Agent details", Entries: []help.Entry{
			{ID: "dialog.agent-details.scroll-read-only-content", Keys: []string{"up", "k", "down", "j", "pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll read-only content", Condition: "content"},
			{ID: "dialog.agent-details.dismiss", Keys: []string{"esc", "enter", "q"}, Description: "Dismiss", Condition: "content"},
		}},
		{ID: "dialog.attachment-preview", Title: "Attachment preview", Entries: []help.Entry{
			{ID: "dialog.attachment-preview.scroll-read-only-content", Keys: []string{"up", "k", "down", "j", "pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll read-only content", Condition: "content"},
			{ID: "dialog.attachment-preview.dismiss", Keys: []string{"esc", "enter", "q"}, Description: "Dismiss", Condition: "content"},
		}},
		{ID: "dialog.permissions", Title: "Permissions", Entries: []help.Entry{
			{ID: "dialog.permissions.scroll-read-only-content", Keys: []string{"up", "k", "down", "j", "pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll read-only content", Condition: "content"},
			{ID: "dialog.permissions.dismiss", Keys: []string{"esc", "enter", "q"}, Description: "Dismiss", Condition: "content"},
		}},
		{ID: "dialog.skills", Title: "Skills", Entries: []help.Entry{
			{ID: "dialog.skills.scroll-read-only-content", Keys: []string{"up", "k", "down", "j", "pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll read-only content", Condition: "content"},
			{ID: "dialog.skills.dismiss", Keys: []string{"esc", "enter", "q"}, Description: "Dismiss", Condition: "content"},
		}},
		{ID: "dialog.tools", Title: "Tools", Entries: []help.Entry{
			{ID: "dialog.tools.scroll-read-only-content", Keys: []string{"up", "k", "down", "j", "pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll read-only content", Condition: "content"},
			{ID: "dialog.tools.dismiss", Keys: []string{"esc", "enter", "q"}, Description: "Dismiss", Condition: "content"},
		}},
		{ID: "dialog.exit-confirmation", Title: "Exit confirmation", Entries: []help.Entry{
			{ID: "dialog.exit-confirmation.affirmative-decision", Keys: []string{"y", "Y"}, Description: "Exit application", Condition: "content"},
			{ID: "dialog.exit-confirmation.negative-cancel-decision", Keys: []string{"n", "N", "esc"}, Description: "Negative/cancel decision", Condition: "Default No; cancellation never affirms."},
			{ID: "dialog.exit-confirmation.selected-default-decision", Keys: []string{"enter"}, Description: "Selected/default decision", Condition: "content default No or action focus"},
			{ID: "dialog.exit-confirmation.enter-default-action-focus-then-move", Keys: []string{"left", "up", "right", "down"}, Description: "Enter default action focus then move", Condition: "content"},
			{ID: "dialog.exit-confirmation.confirm-exit", Keys: []string{"ctrl+c"}, Description: "Confirm exit", Condition: "Configured Quit in exit confirmation, including while opening."},
		}},
		{ID: "dialog.subagents", Title: "Subagents", Entries: []help.Entry{
			{ID: "dialog.subagents.navigate", Keys: []string{"up", "k", "down", "j", "home", "end", "pgup", "pgdown"}, Description: "Select a session", Condition: "content"},
			{ID: "dialog.subagents.fold", Keys: []string{"left", "h", "right", "l", "space"}, Description: "Collapse or expand a branch", Condition: "content"},
			{ID: "dialog.subagents.attach", Keys: []string{"enter"}, Description: "Attach to the selected session", Condition: "content"},
			{ID: "dialog.subagents.toggle", Keys: []string{"u"}, Description: "Save and toggle Use subagents (default ON)", Condition: "Existing work and manual attachment remain available."},
			{ID: "dialog.subagents.close", Keys: []string{"esc", "q", "ctrl+c"}, Description: "Close without cancelling work", Condition: "content"},
		}},
		{ID: "dialog.close-root-with-subagents", Title: "Close root with attached sessions", Entries: []help.Entry{
			{ID: "dialog.close-root-with-subagents.affirmative-decision", Keys: []string{"y", "Y"}, Description: "Close root; retain attached views", Condition: "content"},
			{ID: "dialog.close-root-with-subagents.negative-cancel-decision", Keys: []string{"n", "N", "esc"}, Description: "Negative/cancel decision", Condition: "Default No; Yes closes only this root, without cascading attached views."},
			{ID: "dialog.close-root-with-subagents.selected-default-decision", Keys: []string{"enter"}, Description: "Selected/default decision", Condition: "content default No or action focus"},
			{ID: "dialog.close-root-with-subagents.enter-default-action-focus-then-move", Keys: []string{"left", "up", "right", "down"}, Description: "Enter default action focus then move", Condition: "content"},
		}},
		{ID: "dialog.max-iterations", Title: "Maximum iterations", Entries: []help.Entry{
			{ID: "dialog.max-iterations.affirmative-decision", Keys: []string{"y", "Y"}, Description: "Continue beyond iteration limit", Condition: "content"},
			{ID: "dialog.max-iterations.negative-cancel-decision", Keys: []string{"n", "N", "esc"}, Description: "Negative/cancel decision", Condition: "Default No; response is correlated to the request."},
			{ID: "dialog.max-iterations.selected-default-decision", Keys: []string{"enter"}, Description: "Selected/default decision", Condition: "content default No or action focus"},
			{ID: "dialog.max-iterations.enter-default-action-focus-then-move", Keys: []string{"left", "up", "right", "down"}, Description: "Enter default action focus then move", Condition: "content"},
		}},
		{ID: "dialog.oauth-authorization", Title: "OAuth authorization", Entries: []help.Entry{
			{ID: "dialog.oauth-authorization.affirmative-decision", Keys: []string{"y", "Y"}, Description: "Authorize OAuth", Condition: "content"},
			{ID: "dialog.oauth-authorization.negative-cancel-decision", Keys: []string{"n", "N", "esc"}, Description: "Negative/cancel decision", Condition: "Default Decline; response is correlated to the request."},
			{ID: "dialog.oauth-authorization.selected-default-decision", Keys: []string{"enter"}, Description: "Selected/default decision", Condition: "content default No or action focus"},
			{ID: "dialog.oauth-authorization.enter-default-action-focus-then-move", Keys: []string{"left", "up", "right", "down"}, Description: "Enter default action focus then move", Condition: "content"},
		}},
		{ID: "dialog.plan-delete-confirmation", Title: "Delete plan confirmation", Entries: []help.Entry{
			{ID: "dialog.plan-delete-confirmation.affirmative-decision", Keys: []string{"y", "Y"}, Description: "Delete plan", Condition: "content"},
			{ID: "dialog.plan-delete-confirmation.negative-cancel-decision", Keys: []string{"n", "N", "esc"}, Description: "Negative/cancel decision", Condition: "Default No."},
			{ID: "dialog.plan-delete-confirmation.selected-default-decision", Keys: []string{"enter"}, Description: "Selected/default decision", Condition: "content default No or action focus"},
			{ID: "dialog.plan-delete-confirmation.no-content-navigation-arrows-navigate-only-after-tab-enters-actions", Keys: []string{"left", "up", "right", "down"}, Description: "No content navigation; arrows navigate only after Tab enters actions", Condition: "Unavailable in content; Tab must first enter the action section."},
		}},
		{ID: "dialog.tool-confirmation", Title: "Tool approval", Entries: []help.Entry{
			{ID: "dialog.tool-confirmation.approve-once", Keys: []string{"y", "Y"}, Description: "Approve once", Condition: "Unanswered request; approval once."},
			{ID: "dialog.tool-confirmation.deny-immediately", Keys: []string{"n", "N"}, Description: "Deny immediately", Condition: "Unanswered request; denial once."},
			{ID: "dialog.tool-confirmation.approve-and-always-allow-tool-pattern", Keys: []string{"t", "T"}, Description: "Approve and always allow tool pattern", Condition: "Unanswered request; also changes the tool permission."},
			{ID: "dialog.tool-confirmation.approve-and-enable-balanced", Keys: []string{"b", "B"}, Description: "Approve and enable Balanced", Condition: "Unanswered request; also enables Balanced permissions."},
			{ID: "dialog.tool-confirmation.approve-and-allow-all-tools", Keys: []string{"a", "A"}, Description: "Approve and allow all tools", Condition: "Unanswered request; also allows all tools."},
			{ID: "dialog.tool-confirmation.open-rejection-reason-child-leave-parent-unanswered", Keys: []string{"r", "R"}, Description: "Open rejection reason child, leave parent unanswered", Condition: "Unanswered request; canceling the reason child leaves this approval unanswered."},
			{ID: "dialog.tool-confirmation.promote-default-no-into-action-section-enter-denies-arrows-move", Keys: []string{"enter", "left", "right", "up", "down"}, Description: "Promote default No into action section; Enter denies, arrows move", Condition: "Content default No; arrows enter actions without approving."},
		}},
		{ID: "dialog.command-palette", Title: "Command palette", Entries: []help.Entry{
			{ID: "dialog.command-palette.select-previous-next-bounded-row", Keys: []string{"up", "ctrl+k", "down", "ctrl+j"}, Description: "Select previous/next bounded row", Condition: "content/filter"},
			{ID: "dialog.command-palette.scroll-list-viewport-does-not-move-selected-row", Keys: []string{"pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll list viewport (does not move selected row)", Condition: "Content; Home/End scroll the list rather than moving the filter cursor."},
			{ID: "dialog.command-palette.activate-selected-row", Keys: []string{"enter", "double left click row"}, Description: "Execute selected command", Condition: "selection exists"},
			{ID: "dialog.command-palette.edit-filter", Keys: []string{"text", "paste"}, Description: "Edit filter", Condition: "Filter input; plain j/k insert text, not list navigation."},
			{ID: "dialog.command-palette.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.line-start", Keys: []string{"ctrl+a"}, Description: "Line start", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.line-end", Keys: []string{"ctrl+e"}, Description: "Line end", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.command-palette.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Focused text input; content section, after dialog navigation overrides."},
		}},
		{ID: "dialog.file-picker", Title: "Files", Entries: []help.Entry{
			{ID: "dialog.file-picker.select-previous-next-bounded-row", Keys: []string{"up", "ctrl+k", "down", "ctrl+j"}, Description: "Select previous/next bounded row", Condition: "content/filter"},
			{ID: "dialog.file-picker.scroll-list-viewport-does-not-move-selected-row", Keys: []string{"pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll list viewport (does not move selected row)", Condition: "Content; Home/End scroll the list rather than moving the filter cursor."},
			{ID: "dialog.file-picker.activate-selected-row", Keys: []string{"enter", "double left click row"}, Description: "Enter directory or insert file reference", Condition: "selection exists"},
			{ID: "dialog.file-picker.edit-filter", Keys: []string{"text", "paste"}, Description: "Edit filter", Condition: "Filter input; plain j/k insert text, not list navigation."},
			{ID: "dialog.file-picker.toggle-hidden-files", Keys: []string{"alt+h", "˙", "alt+˙"}, Description: "Toggle hidden files", Condition: "File filter; includes the macOS Option-key aliases."},
			{ID: "dialog.file-picker.toggle-ignored-files", Keys: []string{"alt+i", "ˆ", "alt+ˆ", "̂", "alt+̂"}, Description: "Toggle ignored files", Condition: "File filter; includes spacing and combining circumflex aliases."},
			{ID: "dialog.file-picker.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.line-start", Keys: []string{"ctrl+a"}, Description: "Line start", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.line-end", Keys: []string{"ctrl+e"}, Description: "Line end", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.file-picker.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Focused text input; content section, after dialog navigation overrides."},
		}},
		{ID: "dialog.model-picker", Title: "Models", Entries: []help.Entry{
			{ID: "dialog.model-picker.select-previous-next-bounded-row", Keys: []string{"up", "ctrl+k", "down", "ctrl+j"}, Description: "Select previous/next bounded row", Condition: "content/filter"},
			{ID: "dialog.model-picker.scroll-list-viewport-does-not-move-selected-row", Keys: []string{"pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll list viewport (does not move selected row)", Condition: "Content; Home/End scroll the list rather than moving the filter cursor."},
			{ID: "dialog.model-picker.activate-selected-row", Keys: []string{"enter", "double left click row"}, Description: "Choose selected model", Condition: "selection exists"},
			{ID: "dialog.model-picker.edit-filter", Keys: []string{"text", "paste"}, Description: "Edit filter", Condition: "Filter input; plain j/k insert text, not list navigation."},
			{ID: "dialog.model-picker.refresh-model-catalog-with-current-query", Keys: []string{"ctrl+r"}, Description: "Refresh model catalog with current query", Condition: "content"},
			{ID: "dialog.model-picker.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.line-start", Keys: []string{"ctrl+a"}, Description: "Line start", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.line-end", Keys: []string{"ctrl+e"}, Description: "Line end", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.model-picker.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Focused text input; content section, after dialog navigation overrides."},
		}},
		{ID: "dialog.theme-picker", Title: "Themes", Entries: []help.Entry{
			{ID: "dialog.theme-picker.select-previous-next-bounded-row", Keys: []string{"up", "ctrl+k", "down", "ctrl+j"}, Description: "Select previous/next bounded row", Condition: "content/filter"},
			{ID: "dialog.theme-picker.scroll-list-viewport-does-not-move-selected-row", Keys: []string{"pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll list viewport (does not move selected row)", Condition: "Content; Home/End scroll the list rather than moving the filter cursor."},
			{ID: "dialog.theme-picker.activate-selected-row", Keys: []string{"enter", "double left click row"}, Description: "Confirm selected theme", Condition: "selection exists"},
			{ID: "dialog.theme-picker.edit-filter", Keys: []string{"text", "paste"}, Description: "Edit filter", Condition: "Filter input; plain j/k insert text, not list navigation."},
			{ID: "dialog.theme-picker.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.line-start", Keys: []string{"ctrl+a"}, Description: "Line start", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.line-end", Keys: []string{"ctrl+e"}, Description: "Line end", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.theme-picker.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Focused text input; content section, after dialog navigation overrides."},
		}},
		{ID: "dialog.session-browser", Title: "Sessions", Entries: []help.Entry{
			{ID: "dialog.session-browser.select-previous-next-bounded-row", Keys: []string{"up", "ctrl+k", "down", "ctrl+j"}, Description: "Select previous/next bounded row", Condition: "content/filter"},
			{ID: "dialog.session-browser.scroll-list-viewport-does-not-move-selected-row", Keys: []string{"pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll list viewport (does not move selected row)", Condition: "Content; Home/End scroll the list rather than moving the filter cursor."},
			{ID: "dialog.session-browser.activate-selected-row", Keys: []string{"enter", "double left click row"}, Description: "Load selected session", Condition: "selection exists"},
			{ID: "dialog.session-browser.edit-filter", Keys: []string{"text", "paste"}, Description: "Edit filter", Condition: "Filter input; plain j/k insert text, not list navigation."},
			{ID: "dialog.session-browser.toggle-selected-star", Keys: []string{"ctrl+s"}, Description: "Toggle selected star", Condition: "A session is selected."},
			{ID: "dialog.session-browser.cycle-three-star-filters", Keys: []string{"ctrl+f"}, Description: "Cycle three star filters", Condition: "Cycles All / Starred / Unstarred."},
			{ID: "dialog.session-browser.cycle-three-workspace-filters", Keys: []string{"ctrl+g"}, Description: "Cycle three workspace filters", Condition: "Workspace support is available; otherwise unavailable."},
			{ID: "dialog.session-browser.copy-selected-session-id", Keys: []string{"ctrl+y"}, Description: "Copy selected session ID", Condition: "A session is selected."},
			{ID: "dialog.session-browser.delete-selected-session-immediately", Keys: []string{"ctrl+d"}, Description: "Delete selected session immediately", Condition: "A session is selected; deletes immediately, without a confirmation."},
			{ID: "dialog.session-browser.editing.character-forward", Keys: []string{"right"}, Description: "Character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.delete-character-forward", Keys: []string{"delete"}, Description: "Delete character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.line-start", Keys: []string{"ctrl+a"}, Description: "Line start", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.line-end", Keys: []string{"ctrl+e"}, Description: "Line end", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.session-browser.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Focused text input; content section, after dialog navigation overrides."},
		}},
		{ID: "dialog.plan-browser", Title: "Plans", Entries: []help.Entry{
			{ID: "dialog.plan-browser.select-previous-next-bounded-row", Keys: []string{"up", "ctrl+k", "down", "ctrl+j"}, Description: "Select previous/next bounded row", Condition: "content/filter"},
			{ID: "dialog.plan-browser.scroll-list-viewport-does-not-move-selected-row", Keys: []string{"pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll list viewport (does not move selected row)", Condition: "Content; Home/End scroll the list rather than moving the filter cursor."},
			{ID: "dialog.plan-browser.activate-selected-row", Keys: []string{"enter", "double left click row"}, Description: "Open selected plan details; finish filtering", Condition: "selection exists"},
			{ID: "dialog.plan-browser.focus-filter", Keys: []string{"/"}, Description: "Focus filter", Condition: "not filtering"},
			{ID: "dialog.plan-browser.refresh", Keys: []string{"r"}, Description: "Refresh", Condition: "not filtering"},
			{ID: "dialog.plan-browser.export-selected", Keys: []string{"x"}, Description: "Export selected", Condition: "Not filtering; a plan is selected."},
			{ID: "dialog.plan-browser.open-status-child", Keys: []string{"s"}, Description: "Open status child", Condition: "Not filtering; a versioned shared plan is selected."},
			{ID: "dialog.plan-browser.open-delete-confirmation-child", Keys: []string{"d"}, Description: "Open delete confirmation child", Condition: "Not filtering; a versioned shared plan is selected."},
			{ID: "dialog.plan-browser.open-new-plan-name-child", Keys: []string{"n"}, Description: "Open new plan name child", Condition: "not filtering"},
			{ID: "dialog.plan-browser.edit-selected", Keys: []string{"e"}, Description: "Edit selected", Condition: "Not filtering; a versioned shared plan is selected."},
			{ID: "dialog.plan-browser.edit-filter", Keys: []string{"text", "paste"}, Description: "Edit filter", Condition: "filtering"},
			{ID: "dialog.plan-browser.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.line-start", Keys: []string{"ctrl+a"}, Description: "Line start", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.line-end", Keys: []string{"ctrl+e"}, Description: "Line end", Condition: "Filter mode and input focused; content section."},
			{ID: "dialog.plan-browser.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Filter mode and input focused; content section."},
		}},
		{ID: "dialog.plan-status", Title: "Plan status", Entries: []help.Entry{
			{ID: "dialog.plan-status.validate-nonempty-status-valid-name-then-submit", Keys: []string{"enter"}, Description: "Validate nonempty status / valid name then submit", Condition: "Input nonempty; submits status."},
			{ID: "dialog.plan-status.cancel", Keys: []string{"esc", "mouse ×"}, Description: "Cancel", Condition: "content"},
			{ID: "dialog.plan-status.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.delete-after-cursor", Keys: []string{"ctrl+k"}, Description: "Delete after cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.line-start", Keys: []string{"home", "ctrl+a"}, Description: "Line start", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.line-end", Keys: []string{"end", "ctrl+e"}, Description: "Line end", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-status.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Focused text input; content section, after dialog navigation overrides."},
		}},
		{ID: "dialog.plan-name", Title: "New plan", Entries: []help.Entry{
			{ID: "dialog.plan-name.validate-nonempty-status-valid-name-then-submit", Keys: []string{"enter"}, Description: "Validate nonempty status / valid name then submit", Condition: "Valid nonempty plan name."},
			{ID: "dialog.plan-name.cancel", Keys: []string{"esc", "mouse ×"}, Description: "Cancel", Condition: "content"},
			{ID: "dialog.plan-name.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.delete-after-cursor", Keys: []string{"ctrl+k"}, Description: "Delete after cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.line-start", Keys: []string{"home", "ctrl+a"}, Description: "Line start", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.line-end", Keys: []string{"end", "ctrl+e"}, Description: "Line end", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.plan-name.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Focused text input; content section, after dialog navigation overrides."},
		}},
		{ID: "dialog.plan-detail", Title: "Plan details", Entries: []help.Entry{
			{ID: "dialog.plan-detail.scroll-content", Keys: []string{"up", "k", "down", "j", "pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll content", Condition: "content"},
			{ID: "dialog.plan-detail.close", Keys: []string{"esc", "q"}, Description: "Close", Condition: "Content; Escape safely dismisses from either section."},
			{ID: "dialog.plan-detail.refresh", Keys: []string{"r"}, Description: "Refresh", Condition: "content"},
			{ID: "dialog.plan-detail.export", Keys: []string{"x"}, Description: "Export", Condition: "content"},
			{ID: "dialog.plan-detail.status-child", Keys: []string{"s"}, Description: "Status child", Condition: "A versioned shared plan is displayed."},
			{ID: "dialog.plan-detail.delete-child", Keys: []string{"d"}, Description: "Delete child", Condition: "A versioned shared plan is displayed."},
			{ID: "dialog.plan-detail.edit", Keys: []string{"e"}, Description: "Edit", Condition: "A versioned shared plan is displayed."},
		}},
		{ID: "dialog.context", Title: "Context and attachments", Entries: []help.Entry{
			{ID: "dialog.context.select-bounded-live-session-attachment-row-else-scroll", Keys: []string{"up", "k", "down", "j"}, Description: "Select bounded live-session/attachment row, else scroll", Condition: "content"},
			{ID: "dialog.context.compact-selected-live-session", Keys: []string{"enter"}, Description: "Compact selected live session", Condition: "A live session is selected; Enter does not dismiss an attachment or empty selection."},
			{ID: "dialog.context.drop-selected-attachment", Keys: []string{"d", "x", "backspace", "delete"}, Description: "Drop selected attachment", Condition: "An attachment is selected."},
			{ID: "dialog.context.copy-full-context-breakdown", Keys: []string{"c"}, Description: "Copy full context breakdown", Condition: "content"},
			{ID: "dialog.context.close", Keys: []string{"esc", "q"}, Description: "Close", Condition: "content"},
			{ID: "dialog.context.scroll-viewport", Keys: []string{"pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll viewport", Condition: "content"},
		}},
		{ID: "dialog.cost", Title: "Cost", Entries: []help.Entry{
			{ID: "dialog.cost.scroll-cost", Keys: []string{"up", "k", "down", "j", "pgup", "pgdown", "home", "end", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll cost", Condition: "content"},
			{ID: "dialog.cost.copy-cost-breakdown", Keys: []string{"c"}, Description: "Copy cost breakdown", Condition: "content"},
			{ID: "dialog.cost.close", Keys: []string{"esc", "enter", "q"}, Description: "Dismiss cost", Condition: "Content only; action-focused Enter instead copies."},
		}},
		{ID: "dialog.effort-picker", Title: "Thinking level", Entries: []help.Entry{
			{ID: "dialog.effort-picker.previous-next-bounded-row", Keys: []string{"up", "k", "down", "j"}, Description: "Previous/next bounded row", Condition: "content"},
			{ID: "dialog.effort-picker.first-last-row", Keys: []string{"home", "g", "end", "G"}, Description: "First/last row", Condition: "content"},
			{ID: "dialog.effort-picker.cancel-close", Keys: []string{"esc", "q"}, Description: "Cancel/close", Condition: "content"},
			{ID: "dialog.effort-picker.select-row", Keys: []string{"mouse row click"}, Description: "Select row", Condition: "Selects only; Enter applies."},
			{ID: "dialog.effort-picker.previous-next-bounded-selectable-row", Keys: []string{"ctrl+k", "ctrl+j"}, Description: "Previous/next bounded selectable row", Condition: "content"},
			{ID: "dialog.effort-picker.apply-selected-thinking-level-and-close", Keys: []string{"enter"}, Description: "Apply selected thinking level and close", Condition: "content"},
		}},
		{ID: "dialog.snapshot", Title: "Snapshots", Entries: []help.Entry{
			{ID: "dialog.snapshot.previous-next-bounded-row", Keys: []string{"up", "k", "down", "j"}, Description: "Previous/next bounded row", Condition: "content"},
			{ID: "dialog.snapshot.first-last-row", Keys: []string{"home", "g", "end", "G"}, Description: "First/last row", Condition: "content"},
			{ID: "dialog.snapshot.cancel-close", Keys: []string{"esc", "q"}, Description: "Cancel/close", Condition: "content"},
			{ID: "dialog.snapshot.select-row", Keys: []string{"mouse row click"}, Description: "Select row", Condition: "Selects only; r restores."},
			{ID: "dialog.snapshot.restore-snapshot-keeping-selected-count", Keys: []string{"r"}, Description: "Restore snapshot keeping selected count", Condition: "Snapshots exist; content Enter does nothing. Enter restores only with Restore action focused."},
		}},
		{ID: "dialog.settings", Title: "Settings", Entries: []help.Entry{
			{ID: "dialog.settings.previous-next-bounded-row", Keys: []string{"up", "k", "down", "j", "ctrl+k", "ctrl+j"}, Description: "Previous/next enabled row", Condition: "Controls; bounded navigation."},
			{ID: "dialog.settings.first-last-row", Keys: []string{"home", "g", "end", "G"}, Description: "First/last enabled row", Condition: "Controls."},
			{ID: "dialog.settings.cancel-close", Keys: []string{"esc", "q"}, Description: "Cancel and restore previews", Condition: "Any selected target."},
			{ID: "dialog.settings.select-row", Keys: []string{"mouse row click"}, Description: "Focus a row; toggles/theme activate, enum arrows adjust", Condition: "Visible enabled controls only."},
			{ID: "dialog.settings.focus-zone", Keys: []string{"tab", "shift+tab"}, Description: "Next/previous focus zone", Condition: "All zones: Categories → Controls → Footer; arrows stay within the active zone."},
			{ID: "dialog.settings.categories", Keys: []string{"left", "h", "right", "l"}, Description: "Previous/next category", Condition: "Categories; each remembers its selected row."},
			{ID: "dialog.settings.enter-controls", Keys: []string{"enter", "space"}, Description: "Enter category controls", Condition: "Categories."},
			{ID: "dialog.settings.adjust-setting", Keys: []string{"left", "h", "right", "l"}, Description: "Adjust selected enum or number", Condition: "Controls; numeric bounds apply."},
			{ID: "dialog.settings.activate-setting", Keys: []string{"enter", "space"}, Description: "Toggle, advance, or choose theme; never save", Condition: "Controls; display changes preview until Save. Auto-approve requires confirmation."},
			{ID: "dialog.settings.reorder-panel", Keys: []string{"ctrl+up", "ctrl+down"}, Description: "Reorder selected panel element", Condition: "Controls in Panel."},
			{ID: "dialog.settings.save-settings-and-close", Keys: []string{"enter", "space", "mouse action pill"}, Description: "Save settings and close", Condition: "Save action focused or clicked; Ctrl+S is unbound."},
			{ID: "dialog.settings.scroll-body", Keys: []string{"pgup", "pgdown", "mouse wheel", "scrollbar click/drag"}, Description: "Scroll without moving selection", Condition: "Visible body."},
		}},
		{ID: "dialog.working-dir-picker", Title: "Working directory", Entries: []help.Entry{
			{ID: "dialog.working-dir-picker.cycle-browse-recent-pinned-then-action-section-at-outer-boundaries", Keys: []string{"tab", "shift+tab"}, Description: "Cycle Browse/Recent/Pinned then action section at outer boundaries", Condition: "content"},
			{ID: "dialog.working-dir-picker.move-selected-directory-row", Keys: []string{"up", "ctrl+k", "down", "ctrl+j"}, Description: "Move selected directory row", Condition: "current section"},
			{ID: "dialog.working-dir-picker.scroll-active-section-viewport", Keys: []string{"pgup", "pgdown", "home", "end"}, Description: "Scroll active section viewport", Condition: "Scrolls viewport, not selected row; earlier scrolling shadows the old page-selection branch."},
			{ID: "dialog.working-dir-picker.enter-directory-choose-selected-directory", Keys: []string{"enter", "double left click row"}, Description: "Enter directory / choose selected directory", Condition: "Browse: enters directory or chooses current directory; Recent/Pinned: chooses selected directory."},
			{ID: "dialog.working-dir-picker.pin-unpin-current-target", Keys: []string{"ctrl+p"}, Description: "Pin/unpin current target", Condition: "A pinnable directory is selected; parent-directory row cannot be pinned."},
			{ID: "dialog.working-dir-picker.filter-directories", Keys: []string{"text", "paste"}, Description: "Filter directories", Condition: "Browse section only"},
			{ID: "dialog.working-dir-picker.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.line-start", Keys: []string{"ctrl+a"}, Description: "Line start", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.line-end", Keys: []string{"ctrl+e"}, Description: "Line end", Condition: "Browse section filter focused; content section."},
			{ID: "dialog.working-dir-picker.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Browse section filter focused; content section."},
		}},
		{ID: "dialog.elicitation", Title: "Requested information", Entries: []help.Entry{
			{ID: "dialog.elicitation.next-previous-field-actions-at-first-last-boundary", Keys: []string{"tab", "shift+tab"}, Description: "Next/previous field, actions at first/last boundary", Condition: "content"},
			{ID: "dialog.elicitation.cycle-boolean-enum-option", Keys: []string{"up", "down", "space"}, Description: "Cycle boolean/enum option", Condition: "Boolean/enum field selected; up/down are swallowed on text fields, where space inserts text."},
			{ID: "dialog.elicitation.validate-and-submit", Keys: []string{"enter"}, Description: "Validate and submit", Condition: "Content; invalid fields show validation errors instead of submitting."},
			{ID: "dialog.elicitation.edit-focused-input-select-field-option", Keys: []string{"text", "paste", "mouse field/option click"}, Description: "Edit focused input/select field/option", Condition: "content only"},
			{ID: "dialog.elicitation.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.delete-after-cursor", Keys: []string{"ctrl+k"}, Description: "Delete after cursor", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.line-start", Keys: []string{"home", "ctrl+a"}, Description: "Line start", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.line-end", Keys: []string{"end", "ctrl+e"}, Description: "Line end", Condition: "Text/freeform field focused; content section."},
			{ID: "dialog.elicitation.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Text/freeform field focused; content section."},
		}},
		{ID: "dialog.mcp-prompt-input", Title: "MCP prompt arguments", Entries: []help.Entry{
			{ID: "dialog.mcp-prompt-input.move-between-arguments-tab-actions-at-first-last", Keys: []string{"up", "shift+tab", "down", "tab"}, Description: "Move between arguments, Tab actions at first/last", Condition: "content"},
			{ID: "dialog.mcp-prompt-input.execute-prompt-with-trimmed-arguments", Keys: []string{"enter"}, Description: "Execute prompt with trimmed arguments", Condition: "All required arguments are filled."},
			{ID: "dialog.mcp-prompt-input.edit-selected-argument", Keys: []string{"text", "paste", "mouse input click"}, Description: "Edit selected argument", Condition: "content focused"},
			{ID: "dialog.mcp-prompt-input.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.delete-after-cursor", Keys: []string{"ctrl+k"}, Description: "Delete after cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.line-start", Keys: []string{"home", "ctrl+a"}, Description: "Line start", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.line-end", Keys: []string{"end", "ctrl+e"}, Description: "Line end", Condition: "Focused text input; content section, after dialog navigation overrides."},
			{ID: "dialog.mcp-prompt-input.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Focused text input; content section, after dialog navigation overrides."},
		}},
		{ID: "dialog.multi-choice-tool-rejection-reason", Title: "Choices and rejection reason", Entries: []help.Entry{
			{ID: "dialog.multi-choice-tool-rejection-reason.cycle-options-custom-none-and-actions-at-boundaries", Keys: []string{"up", "down", "tab", "shift+tab"}, Description: "Cycle options/custom/none and actions at boundaries", Condition: "content"},
			{ID: "dialog.multi-choice-tool-rejection-reason.select-first-ten-options-or-custom-slot", Keys: []string{"1", "2", "3", "4", "5", "6", "7", "8", "9", "0"}, Description: "Select first ten options or custom slot", Condition: "Not editing custom text; available first ten options/custom slot only. Numbers select, never submit."},
			{ID: "dialog.multi-choice-tool-rejection-reason.submit-primary", Keys: []string{"ctrl+enter"}, Description: "Submit primary", Condition: "Valid selection/custom text; unanswered."},
			{ID: "dialog.multi-choice-tool-rejection-reason.submit-secondary-skip", Keys: []string{"ctrl+s"}, Description: "Submit secondary/Skip", Condition: "Secondary action is allowed; unanswered."},
			{ID: "dialog.multi-choice-tool-rejection-reason.submit-dynamic-default", Keys: []string{"enter"}, Description: "Submit dynamic default", Condition: "Content default follows selection and secondary preference; action-focused Enter follows selected action."},
			{ID: "dialog.multi-choice-tool-rejection-reason.edit-custom-typing-may-auto-select-custom", Keys: []string{"text", "paste"}, Description: "Edit custom; typing may auto-select custom", Condition: "Custom input allowed; no editing or paste in action section. Reason-child Escape leaves approval unanswered."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.delete-after-cursor", Keys: []string{"ctrl+k"}, Description: "Delete after cursor", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.line-start", Keys: []string{"home", "ctrl+a"}, Description: "Line start", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.line-end", Keys: []string{"end", "ctrl+e"}, Description: "Line end", Condition: "Custom text input focused and allowed; content section."},
			{ID: "dialog.multi-choice-tool-rejection-reason.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Custom text input focused and allowed; content section."},
		}},
		{ID: "dialog.pending-message-edit", Title: "Pending message draft", Entries: []help.Entry{
			{ID: "dialog.pending-message-edit.save-full-draft", Keys: []string{"enter", "ctrl+enter"}, Description: "Save full draft", Condition: "Not saving or closed; save callback exists. Errors retain the draft."},
			{ID: "dialog.pending-message-edit.edit-multiline-draft", Keys: []string{"text", "paste"}, Description: "Edit multiline draft", Condition: "Content focused, not saving; Shift+Enter/Ctrl+J inserts a newline. Tab/Shift+Tab crosses to actions."},
			{ID: "dialog.pending-message-edit.editing.character-forward", Keys: []string{"right", "ctrl+f"}, Description: "Character forward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.character-backward", Keys: []string{"left", "ctrl+b"}, Description: "Character backward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.word-forward", Keys: []string{"alt+right", "ctrl+right", "alt+f"}, Description: "Word forward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.word-backward", Keys: []string{"alt+left", "ctrl+left", "alt+b"}, Description: "Word backward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.line-next", Keys: []string{"down", "ctrl+n"}, Description: "Line next", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.line-previous", Keys: []string{"up", "ctrl+p"}, Description: "Line previous", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.delete-word-backward", Keys: []string{"alt+backspace", "ctrl+w", "ctrl+backspace"}, Description: "Delete word backward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.delete-word-forward", Keys: []string{"alt+delete", "alt+d", "ctrl+delete"}, Description: "Delete word forward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.delete-after-cursor", Keys: []string{"ctrl+k"}, Description: "Delete after cursor", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.delete-before-cursor", Keys: []string{"ctrl+u"}, Description: "Delete before cursor", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.insert-newline", Keys: []string{"shift+enter", "ctrl+j"}, Description: "Insert newline", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.delete-character-backward", Keys: []string{"backspace", "ctrl+h"}, Description: "Delete character backward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.delete-character-forward", Keys: []string{"delete", "ctrl+d"}, Description: "Delete character forward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.line-start", Keys: []string{"home", "ctrl+a"}, Description: "Line start", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.line-end", Keys: []string{"end", "ctrl+e"}, Description: "Line end", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.page-up", Keys: []string{"pgup"}, Description: "Page up", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.page-down", Keys: []string{"pgdown"}, Description: "Page down", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.paste", Keys: []string{"ctrl+v"}, Description: "Paste", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.input-begin", Keys: []string{"alt+<", "ctrl+home"}, Description: "Input begin", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.input-end", Keys: []string{"alt+>", "ctrl+end"}, Description: "Input end", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.capitalize-word-forward", Keys: []string{"alt+c"}, Description: "Capitalize word forward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.lowercase-word-forward", Keys: []string{"alt+l"}, Description: "Lowercase word forward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.uppercase-word-forward", Keys: []string{"alt+u"}, Description: "Uppercase word forward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.transpose-character-backward", Keys: []string{"ctrl+t"}, Description: "Transpose character backward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.select-character-forward", Keys: []string{"shift+right"}, Description: "Select character forward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.select-character-backward", Keys: []string{"shift+left"}, Description: "Select character backward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.select-word-forward", Keys: []string{"ctrl+shift+right", "alt+shift+right", "alt+shift+f"}, Description: "Select word forward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.select-word-backward", Keys: []string{"ctrl+shift+left", "alt+shift+left", "alt+shift+b"}, Description: "Select word backward", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.select-line-up", Keys: []string{"shift+up"}, Description: "Select line up", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.select-line-down", Keys: []string{"shift+down"}, Description: "Select line down", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.select-all", Keys: []string{"ctrl+g"}, Description: "Select all", Condition: "Multiline draft focused; not saving or closed; content section."},
			{ID: "dialog.pending-message-edit.editing.copy-selection", Keys: []string{"ctrl+shift+c"}, Description: "Copy selection", Condition: "Multiline draft focused; not saving or closed; content section."},
		}},
		{ID: "dialog.url-elicitation", Title: "URL completion", Entries: []help.Entry{
			{ID: "dialog.url-elicitation.accept-completion", Keys: []string{"y", "Y"}, Description: "Accept completion", Condition: "Unanswered request; Enter acts only with an action focused."},
			{ID: "dialog.url-elicitation.decline", Keys: []string{"n", "N"}, Description: "Decline", Condition: "Unanswered request."},
			{ID: "dialog.url-elicitation.open-url-externally", Keys: []string{"o"}, Description: "Open URL externally", Condition: "A nonempty URL is available."},
			{ID: "dialog.url-elicitation.cancel", Keys: []string{"esc", "mouse ×"}, Description: "Cancel", Condition: "Unanswered request; cancellation never accepts."},
		}},
		{ID: "dialog.tour-offer", Title: "Tour offer", Entries: []help.Entry{
			{ID: "dialog.tour-offer.take-tour", Keys: []string{"enter", "y", "Y"}, Description: "Take tour", Condition: "Content defaults to Take tour; action-focused Enter follows selected action."},
			{ID: "dialog.tour-offer.not-now", Keys: []string{"n", "N", "esc"}, Description: "Not now", Condition: "Not now; does not start the tour."},
			{ID: "dialog.tour-offer.never-offer", Keys: []string{"d", "D"}, Description: "Never offer", Condition: "Never offer the tour again."},
		}},
	}
}
