package leantui

import "github.com/docker/docker-agent/pkg/leantui/ui"

func builtinCommands() []ui.Command {
	return []ui.Command{
		{Name: "resume", Desc: "Resume only this restored, paused session and its queued work", Kind: ui.CmdBuiltin},
		{Name: "panes", Desc: "Pane layouts require the full TUI; unavailable in standalone lean", Kind: ui.CmdBuiltin},
		{Name: "getting-started", Desc: "Interactive visual tour requires the full TUI; use /help here", Kind: ui.CmdBuiltin},
		{Name: "speak", Desc: "Dictate into this draft (macOS audio builds)", Kind: ui.CmdBuiltin},
		{Name: "respond", Desc: "Answer a pending interaction: /respond <request-id> <JSON|cancel>", Kind: ui.CmdBuiltin},
		{Name: "fork", Desc: "Fork the conversation into a new viewer", Kind: ui.CmdBuiltin},
		{Name: "plans", Desc: "Manage shared plans: /plans help", Kind: ui.CmdBuiltin},
		{Name: "settings", Desc: "Manage preferences: /settings", Kind: ui.CmdBuiltin},
		{Name: "attach", Desc: "Attach a file to this viewer draft: /attach <path>", Kind: ui.CmdBuiltin},
		{Name: "drop", Desc: "Drop a draft or session attachment: /drop [path]", Kind: ui.CmdBuiltin},
		{Name: "context", Desc: "Inspect context usage and attachments", Kind: ui.CmdBuiltin},
		{Name: "cost", Desc: "Inspect session cost breakdown", Kind: ui.CmdBuiltin},
		{Name: "pause", Desc: "Pause or resume after the current request", Kind: ui.CmdBuiltin},
		{Name: "permissions", Desc: "Inspect tool permission rules", Kind: ui.CmdBuiltin},
		{Name: "yolo", Desc: "Change automatic approval with explicit confirmation", Kind: ui.CmdBuiltin},
		{Name: "title", Desc: "Set or regenerate the session title", Kind: ui.CmdBuiltin},
		{Name: "export", Desc: "Export session HTML: /export [filename]", Kind: ui.CmdBuiltin},
		{Name: "eval", Desc: "Save evaluation: /eval [filename]", Kind: ui.CmdBuiltin},
		{Name: "tools", Desc: "Inspect toolsets and tools", Kind: ui.CmdBuiltin},
		{Name: "skills", Desc: "List current agent skills", Kind: ui.CmdBuiltin},
		{Name: "toolset-restart", Desc: "Restart a toolset: /toolset-restart <name>", Kind: ui.CmdBuiltin},
		{Name: "snapshots", Desc: "List captured snapshots", Kind: ui.CmdBuiltin},
		{Name: "undo", Desc: "Restore the latest snapshot: /undo confirm", Kind: ui.CmdBuiltin},
		{Name: "shell", Desc: "Run a shell command: /shell <command>", Kind: ui.CmdBuiltin},
		{Name: "subagents", Desc: "List descendant subagents and select a live viewer", Kind: ui.CmdBuiltin},
		{Name: "subagent-view", Desc: "Open live viewer: /subagent-view <exact node or session ID>", Kind: ui.CmdBuiltin},
		{Name: "subagent-attach", Desc: "Open live viewer: /subagent-attach <exact node or session ID>", Kind: ui.CmdBuiltin},
		{Name: "back", Desc: "Return to previous viewer without cancelling execution", Kind: ui.CmdBuiltin},
		{Name: "copy-last", Desc: "Copy the last assistant response", Kind: ui.CmdBuiltin},
		{Name: "copy-session", Desc: "Copy the conversation", Kind: ui.CmdBuiltin},
		{Name: "q", Desc: "Exit", Kind: ui.CmdBuiltin},

		{Name: "new", Desc: "Start a new session", Kind: ui.CmdBuiltin},
		{Name: "sessions", Desc: "Browse/resume sessions from the current directory", Kind: ui.CmdBuiltin},
		{Name: "load", Desc: "Load a session by ID", Kind: ui.CmdBuiltin},
		{Name: "delete", Desc: "Delete a session by ID", Kind: ui.CmdBuiltin},
		{Name: "star", Desc: "Star or unstar a session", Kind: ui.CmdBuiltin},
		{Name: "compact", Desc: "Summarize and compact the conversation", Kind: ui.CmdBuiltin},
		{Name: "model", Desc: "Change the model for the current agent", Kind: ui.CmdBuiltin},
		{Name: "effort", Desc: "Set the model's reasoning effort (usage: /effort <level>)", Kind: ui.CmdBuiltin},
		{Name: "copy", Desc: "Copy the last assistant response", Kind: ui.CmdBuiltin},
		{Name: "clear", Desc: "Clear the screen", Kind: ui.CmdBuiltin},
		{Name: "help", Desc: "Show keyboard shortcuts", Kind: ui.CmdBuiltin},
		{Name: "exit", Desc: "Exit", Kind: ui.CmdBuiltin},
		{Name: "quit", Desc: "Exit", Kind: ui.CmdBuiltin},
	}
}
